baseURL = 'https://willduncan.com'
languageCode = 'en-us'
title = 'William Duncan'
theme = 'baseline'
enableGitInfo = 'true'

[params]
    author = 'William Duncan'
    description = 'Photographer based in Santa Cruz, California'
    phone = '(831)291-3818'
    email = 'hello@coldwaterchapel.com'
    cloudflareID = '0KE9fI8HU0iXQd54xFyZqw'

[permalinks]
  posts = '/:year/:month/:day/:title/'
  '/' = '/:slug/'

[menu]
  [[menu.main]]
    name = 'Posts'
    title = 'posts'
    url = '/posts/'
    weight = 10

  [[menu.main]]
    name = 'About'
    title = 'about'
    url = '/about/'
    weight = 20

  [[menu.main]]
    name = 'Projects'
    title = 'projects'
    url = '/projects/'
    weight = 30

  [[menu.main]]
    name = 'Buy a print'
    title = 'But a print'
    url = '/prints/'
    weight = 40