baseURL = 'https://willduncan.com'
languageCode = 'en-us'
title = 'William Duncan'

theme = 'baseline'
enableGitInfo = "true"

[params]
    author = "William Duncan"
    description = "Photographer based in Santa Cruz, California"
    phone = "(831)291-3818"
    email = "hello@coldwaterchapel.com"